# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: seungmmong
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-image-app

provider:
  name: aws
  runtime: nodejs20.x
  region: ${file(config.json):AWS_REGION}
  environment:
    BUCKET_NAME: ${file(config.json):S3_IMAGE_BUCKET}
    TABLE_NAME: ${file(config.json):DYNAMODB_TABLE_NAME}
  
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:*
        - rekognition:DetectLabels
      Resource:
        - arn:aws:s3:::${file(config.json):S3_IMAGE_BUCKET}/*
package:
  exclude:
    - config.json
    - package.json
    - package-lock.json
    - README.md
    - .gitignore
    - .serverless/**
functions:
  pattyGetSignedUrl:
    handler: handler.getSignedUrl
    events:
      - httpApi:
          path: /signed-url
          method: get

resources:
  Resources:
    UploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BUCKET_NAME}
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
              AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"
              MaxAge: 3000
    ImageTagsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: image
            AttributeType: S
        KeySchema:
          - AttributeName: image
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST